# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: eb1025e
_src_path: ../catalystsquad/copier-chart-registry
githost: github
github_settings: true
organization: networksanitationcommittee
owner_groupname: engineers
